on: 
  push:
  pull_request:
    types: [opened]

name: CI

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      MBTA_TOKEN: ${{ secrets.MBTA_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: 'true'
      - run: cargo test --verbose --all-features
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            lfs: 'true'
      - run: rustup component add clippy
      - run: rustup component add rustfmt
      - run: cargo clippy --all-features -- -D warnings
      - run: cargo fmt --all -- --check
  conventional-commits:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            lfs: 'true'
      - uses: webiny/action-conventional-commits@v1.0.3
